[package]
name = "tsg-metadata"
authors = ["Travis Brown <travisrobertbrown@gmail.com>"]
repository = "https://github.com/travisbrown/tsg-metadata"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "3", features = ["derive"] }
hex = "0.4"
log = "0.4"
roxmltree = "0.14"
simplelog = "0.11"
thiserror = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
